apiVersion: v1
kind: Service
metadata:
  name: {{ include "workshop.fullname" . }}-dev
  labels:
    {{- include "workshop.labels" . | nindent 4 }}
    environment: dev
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app: {{ include "workshop.name" . }}-dev
