apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "workshop.fullname" . }}-dev
  labels:
    {{- include "workshop.labels" . | nindent 4 }}
    environment: dev
spec:
  to:
    kind: Service
    name: {{ include "workshop.fullname" . }}-dev
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
