apiVersion: v1
kind: Secret
metadata:
  name: {{ include "workshop.fullname" . }}-webhook-secret
  labels:
    {{- include "workshop.labels" . | nindent 4 }}
type: Opaque
stringData:
  WebHookSecretKey: {{ .Values.build.webhookSecret | default "secretwebhooktoken123" }}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ include "workshop.fullname" . }}-dev
  labels:
    {{- include "workshop.labels" . | nindent 4 }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: {{ include "workshop.fullname" . }}-dev:latest
  source:
    type: Git
    git:
      uri: http://{{ include "workshop.fullname" . }}-gitea:3000/{{ .Values.gitea.admin.username }}/{{ .Values.build.repoName }}.git
      ref: dev
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: {{ .Values.build.builderImage }}
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: {{ include "workshop.fullname" . }}-webhook-secret
  successfulBuildsHistoryLimit: {{ .Values.build.successfulBuildsHistoryLimit | default 2 }}
  failedBuildsHistoryLimit: {{ .Values.build.failedBuildsHistoryLimit | default 2 }}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ include "workshop.fullname" . }}-prod
  labels:
    {{- include "workshop.labels" . | nindent 4 }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: {{ include "workshop.fullname" . }}-prod:latest
  source:
    type: Git
    git:
      uri: http://{{ include "workshop.fullname" . }}-gitea:3000/{{ .Values.gitea.admin.username }}/{{ .Values.build.repoName }}.git
      ref: main
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: {{ .Values.build.builderImage }}
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: {{ include "workshop.fullname" . }}-webhook-secret
  successfulBuildsHistoryLimit: {{ .Values.build.successfulBuildsHistoryLimit | default 2 }}
  failedBuildsHistoryLimit: {{ .Values.build.failedBuildsHistoryLimit | default 2 }}
