apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "workshop.fullname" . }}-gitea-setup
  labels:
    {{- include "workshop.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: {{ include "workshop.fullname" . }}-gitea-setup
      labels:
        app: {{ include "workshop.name" . }}-gitea-setup
    spec:
      restartPolicy: OnFailure
      containers:
        - name: setup
          image: curlimages/curl:latest
          command: ["/bin/sh", "/mnt/setup.sh"]
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: script-vol
              mountPath: /mnt
      volumes:
        - name: script-vol
          configMap:
            name: {{ include "workshop.fullname" . }}-gitea-setup
            defaultMode: 0755
