apiVersion: v1
kind: Service
metadata:
  name: {{ include "workshop.fullname" . }}-gitea
  labels:
    {{- include "workshop.labels" . | nindent 4 }}
spec:
  type: {{ .Values.gitea.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ .Values.gitea.service.port }}
      targetPort: http
      protocol: TCP
    - name: ssh
      port: {{ .Values.gitea.service.sshPort }}
      targetPort: ssh
      protocol: TCP
  selector:
    app: {{ include "workshop.name" . }}-gitea
