apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "workshop.fullname" . }}-gitserver-start
  labels:
    {{- include "workshop.labels" . | nindent 4 }}
data:
  start.sh: |
{{ .Files.Get "files/gitserver/start.sh" | indent 4 }}
