apiVersion: v1
kind: Secret
metadata:
  name: {{ include "workshop.fullname" . }}-oc-token
  labels:
    {{- include "workshop.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.openshift.token | default "" | quote }}
